# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'XCWeather' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XCWeather
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
end

target 'DoubleBindDemo' do
    use_frameworks!
    pod 'RxSwift'
    pod 'RxCocoa'
end

target '6.1Demo' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for XCWeather
    pod 'RxSwift'
    pod 'RxCocoa'

    pod 'Alamofire'
    pod 'RxDataSources'
end
