# Uncomment the next line to define a global platform for your project
 platform :osx, '10.12'

target '05-FilteringOperation' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 05-FilteringOperation
  pod 'RxSwift'
  pod 'RxCocoa'
end
