# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'ObjcUI' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ObjcUI
#  pod "PromiseKit", "~> 6.0"


end
