# Uncomment the next line to define a global platform for your project
 platform :osx, '10.12'

target 'Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod "PromiseKit", "~>6.0"
  # Pods for Example

end
