# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target '06-XCWeibo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 06-XCWeibo

end

target 'Objc-UI' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Objc-UI
  pod 'SDAutoLayout', '~> 2.1.3'
  pod 'Hyphenate'

end
