# Uncomment the next line to define a global platform for your project
 platform :osx, '10.12'

target '03-RxSwiftMac' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 03-RxSwiftMac
  pod 'RxSwift', '~> 4.0' 
  pod 'RxCocoa', '~> 4.0'
end
